### ISSUE TITLE
Confirmation for options in JCLPCB site when ordering the boards, please

### ISSUE THREAD

**Issue by vanfanel** [eivindbohler/tinyllama#1]
I asked for help on the Vogons forum, but since I think you didn't read my message, I am trying my luck here.

I already ordered the main components (SOC, VGA module, Crystal sound chip), and I am going to order like 5 TinyLlama boards in JCLPCB as per your advice.
I want them to be populated.

So, in the JCLPCB site, I uploaded the .ZIP from "fabrication" in your github, and then set the options like this:
-I have activated **PCB Assembly** <---This is so the board comes with the components soldered, right?
-I have then set **PCBA Type** to **Standard**, so I can set **Assembly Sides** to **Both Sides**.
**The rest of the options available are set to their defaults.**

**Can you please confirm it is all this right?** Will they pick the components automatically with those options? Am I missing something?

Thanks!

**Comment by eivindbohler** [comment]
Answered in detail in the Vogons thread, but to summarize: I deliberately choose not to include any PCB manufacturer-specific details in this repo, as they're very reliant upon up-to-date details and parts inventories which I don't consider belonging to this open source project (and don't have the time to track and document).
